### ISSUE TITLE
Lodash empty export

### ISSUE THREAD

**Issue by akcyp** [orta/playground-dt-review#2]
Hello, I found a problem with using this plugin on my PR to DefinitelyTyped/lodash. When trying to import `debounce` function from `lodash`  I'm getting an error: `Module '"lodash"' has no exported member 'debounce'`.

Check out this example: [https://www.typescriptlang.org/play?&dtPR=56299&install-plugin=playground-dt-review#code/JYWwDg9gTgLgBAbzgEwKYCMIFcB2BjVOAXzgDMoIQ4ByAGwmQEMBnAC2oG4AoIA](https://www.typescriptlang.org/play?&dtPR=56299&install-plugin=playground-dt-review#code/JYWwDg9gTgLgBAbzgEwKYCMIFcB2BjVOAXzgDMoIQ4ByAGwmQEMBnAC2oG4AoIA)

Without plugin: [https://www.typescriptlang.org/play?&install-plugin=playground-dt-review#code/JYWwDg9gTgLgBAbzgEwKYCMIFcB2BjVOAXzgDMoIQ4ByAGwmQEMBnAC2oG4AoIA](https://www.typescriptlang.org/play?&install-plugin=playground-dt-review#code/JYWwDg9gTgLgBAbzgEwKYCMIFcB2BjVOAXzgDMoIQ4ByAGwmQEMBnAC2oG4AoIA)

**Comment by orta** [comment]
Yeah for sure, lodash is a bit of a bonkers set of types - the re-write of type acquisition should hopefully fix it https://github.com/microsoft/TypeScript-Website/pull/1997

**Comment by akcyp** [comment]
I tried with this tag syntax but it didn't work. Could you give an example of how to fix it?

**Comment by orta** [comment]
That pull request is not merged, it's not possible to be fixed until then
